name: 'CI/CD Backend'
on: 
  push:
  pull_request:
    branches:
    - main 
  workflow_dispatch:

jobs:
  push-to-uat:
    runs-on: "ubuntu-latest"
    name: "Push to UAT"
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: use JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      
      - name: build backend
        run: |
          cd backend
          ./gradlew build 
          ./gradlew shadowJar

      - name: deploy to uat
        uses: easingthemes/ssh-deploy@v2.1.5 
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          SOURCE: "backend/build/libs/*.jar"
          REMOTE_HOST: ${{ secrets.HOSTNAME }}
          REMOTE_USER: ${{ secrets.USER }}
          TARGET: "/home/ubuntu/backend/"
  run-bdd:
    runs-on: "ubuntu-latest"
    name: "Test backend"
    needs: push-to-uat
    steps:
      - name: "Checkout branch"
        uses: actions/checkout@v4

      - name: use JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: "Run backend Tests"
        run: |
          cd backend
          ./gradlew test

  push-to-prod:
    runs-on: "ubuntu-latest"
    needs: run-bdd
    name: "Push to Prod"
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: use JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      
      - name: build backend
        run: |
          cd backend
          ./gradlew build 
          ./gradlew shadowJar

      - name: deploy to uat
        uses: easingthemes/ssh-deploy@v2.1.5 
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          SOURCE: "backend/build/libs/*"
          REMOTE_HOST: ${{ secrets.HOSTNAME }}
          REMOTE_USER: ${{ secrets.USER }}
          TARGET: "/home/ubuntu/backend/"