name: 'CI/CD Backend'
on: 
  push:
  pull_request:
    branches:
    - main 
  workflow_dispatch:

jobs:
  push-to-uat:
    runs-on: "ubuntu-latest"
    name: "Push to UAT"
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.100'

      - name: Restore Packages
        run: |
          cd backend
          dotnet restore HaveLunch.sln

      - name: Build Source
        run: |
          cd backend
          dotnet build HaveLunch/HaveLunch.csproj --configuration Release --no-restore

      - name: Publish Backend
        run: |
          cd backend
          dotnet publish HaveLunch/HaveLunch.csproj --configuration Release --no-restore --no-build

      - name: deploy to uat
        uses: easingthemes/ssh-deploy@v2.1.5 
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          SOURCE: "backend/HaveLunch/bin/net8.0/Release/publish/*"
          REMOTE_HOST: ${{ secrets.HOSTNAME }}
          REMOTE_USER: ${{ secrets.USER }}
          TARGET: "/home/ubuntu/backend/dotnet"

  run-tests:
    runs-on: "ubuntu-latest"
    name: "Test backend"
    needs: push-to-uat
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.100'

      - name: Run Tests
        run: |
          cd backend
          dotnet test HaveLunch.Tests/HaveLunch.Tests.csproj

  push-to-prod:
    runs-on: "ubuntu-latest"
    needs: run-bdd
    name: "Push to Prod"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.100'

      - name: Restore Packages
        run: |
          cd backend
          dotnet restore HaveLunch.sln

      - name: Build Source
        run: |
          cd backend
          dotnet build HaveLunch/HaveLunch.csproj --configuration Release --no-restore

      - name: Publish Backend
        run: |
          cd backend
          dotnet publish HaveLunch/HaveLunch.csproj --configuration Release --no-restore --no-build

      - name: deploy to uat
        uses: easingthemes/ssh-deploy@v2.1.5 
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          SOURCE: "backend/build/libs/*"
          REMOTE_HOST: ${{ secrets.HOSTNAME }}
          REMOTE_USER: ${{ secrets.USER }}
          TARGET: "/home/ubuntu/backend/"