name: 'build and test'
on: 
 pull_request:
   branches:
   - main 
 workflow_dispatch:

jobs:
 buildAndtest:
  runs-on: "ubuntu-latest"
  name: "Continuous Integration"
  steps:
  - name: "Checkout branch"
    uses: actions/checkout@v1
  
  - name: "Setup Node"
    uses: actions/setup-node@v3
    with:
      node-version: "20.11.1"
  
  - name: "Install dependencies"
    run: |
      cd frontend
      npm i
  
  - name: "Run Unit tests"
    run: |
      cd frontend
      npm run test
  
