name: 'build and test'
on: 
  push:
  pull_request:
    branches:
    - main 
  workflow_dispatch:

jobs:
  push-to-uat:
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: deploy to uat
        uses: easingthemes/ssh-deploy@v2.1.5 
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          SOURCE: "frontend/src/*"
          REMOTE_HOST: ${{ secrets.HOSTNAME }}
          REMOTE_USER: ${{ secrets.USER }}
          TARGET: "/var/www/html/uat/"
  run-bdd:
    runs-on: "ubuntu-latest"
    name: "Frontend Build"
    needs: push-to-uat
    steps:
    - name: "Checkout branch"
      uses: actions/checkout@v4
    
    - name: "Setup Node"
      uses: actions/setup-node@v3
      with:
        node-version: "20.11.1"
      
    - name: "Install Dependencies"
      run: |
        cd frontend
        npm ci

    - name: "Setup Chrome"
      uses: browser-actions/setup-chrome@v1
      
    - name: "Run Tests"
      run: |
        npm test

  push-to-prod:
    runs-on: "ubuntu-latest"
    needs: push-to-uat
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: deploy to uat
        uses: easingthemes/ssh-deploy@v2.1.5 
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          SOURCE: "frontend/src/*"
          REMOTE_HOST: ${{ secrets.HOSTNAME }}
          REMOTE_USER: ${{ secrets.USER }}
          TARGET: "/var/www/html/prod/"
