name: 'build and test'
on: 
  push:
  pull_request:
    branches:
    - main 
  workflow_dispatch:

jobs:
  push-to-uat:
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: build
        run: |
          cd frontend
          npm ci
          npm run build-uat

      - name: remove previously deployed files
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/html/
            rm -rf uat

      - name: deploy to uat
        uses: easingthemes/ssh-deploy@v2.1.5 
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          SOURCE: "frontend/dist/*"
          REMOTE_HOST: ${{ secrets.HOSTNAME }}
          REMOTE_USER: ${{ secrets.USER }}
          TARGET: "/var/www/html/uat/"

  run-bdd:
    runs-on: "ubuntu-latest"
    name: "Frontend Build"
    needs: push-to-uat
    steps:
    - name: "Checkout branch"
      uses: actions/checkout@v4
    
    - name: "Setup Node"
      uses: actions/setup-node@v3
      with:
        node-version: "20.11.1"
        
    - name: "Install Dependencies"
      run: |
        cd frontend
        npm ci
      env:
        VITE_HOST_URL: ${{ secrets.VITE_HOST_URL }}
        VITE_HOST_PORT: ${{ secrets.VITE_HOST_PORT }}
        PROD: "true"

    - name: "Setup Chrome"
      uses: browser-actions/setup-chrome@v1
      
    - name: "Run Tests"
      run: |
        cd frontend
        npm test
      env:
        VITE_HOST_URL: ${{ secrets.VITE_HOST_URL }}
        VITE_HOST_PORT: ${{ secrets.VITE_HOST_PORT }}
        PROD: "true"

  push-to-prod:
    runs-on: "ubuntu-latest"
    needs: run-bdd
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: build-frontend
        run: |
          cd frontend
          npm ci
          npm run build-prod

      - name: remove previously deployed files
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/html/
            rm -rf prod

      - name: deploy to prod
        uses: easingthemes/ssh-deploy@v2.1.5 
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          PROD: "true"
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_API_PORT: ${{ secrets.VITE_API_PORT }}
          SOURCE: "frontend/dist/*"
          REMOTE_HOST: ${{ secrets.HOSTNAME }}
          REMOTE_USER: ${{ secrets.USER }}
          TARGET: "/var/www/html/prod/"
          BASE_URL: "/prod/"
